name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: StringDuper
          path: target/*.jar
